service: roof-top

frameworkVersion: '3'
 
plugins:
 
provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs16.x
 
functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}